<#
  Infra Monitor -- native install on this machine. No Docker.

  Creates a Python virtualenv, installs the backend dependencies, builds the static UI,
  and prepares .env and the data directory. Run once, then use scripts/native-run.ps1.

  Node is needed only here: it compiles the UI into frontend/out, which the Python
  process then serves. Nothing needs Node at run time.

  Written for Windows PowerShell 5.1, so no &&, no ternary, no null-coalescing.
#>
[CmdletBinding()]
param(
    [switch]$SkipUi,
    [string]$PythonVersion = "3.12"
)

$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent $PSScriptRoot
Set-Location $repo

function Say([string]$text) { Write-Host $text }
function Fail([string]$text) { Write-Host "FAIL  $text" -ForegroundColor Red; exit 1 }
function Ok([string]$text)   { Write-Host "OK    $text" -ForegroundColor Green }

Say ""
Say "Infra Monitor -- native setup in $repo"
Say ("=" * 72)

# --- toolchain -------------------------------------------------------------------
$py = $null
$launcher = Get-Command py -ErrorAction SilentlyContinue
if ($null -ne $launcher) {
    & py "-$PythonVersion" -c "import sys" 2>$null
    if ($?) { $py = @("py", "-$PythonVersion") }
}
if ($null -eq $py) {
    $direct = Get-Command python -ErrorAction SilentlyContinue
    if ($null -ne $direct) {
        $v = & python -c "import sys;print('%d.%d' % sys.version_info[:2])"
        # pydantic evaluates `X | None` in signatures at import, which needs 3.10+
        if ([version]$v -ge [version]"3.10") { $py = @("python") } else { Fail "python on PATH is $v; 3.10 or newer is required." }
    }
}
if ($null -eq $py) { Fail "No suitable Python found. Install Python $PythonVersion and re-run." }
$pyVersion = & $py[0] $py[1..($py.Length - 1)] -c "import sys;print(sys.version.split()[0])"
Ok "Python $pyVersion"

if (-not $SkipUi) {
    $node = Get-Command node -ErrorAction SilentlyContinue
    if ($null -eq $node) { Fail "Node.js not found, and it is needed to build the UI. Install Node 20+, or re-run with -SkipUi if frontend/out already exists." }
    Ok ("Node " + (& node --version))
}

# --- virtualenv ------------------------------------------------------------------
$venv = Join-Path $repo ".venv"
$venvPython = Join-Path $venv "Scripts\python.exe"
if (-not (Test-Path $venvPython)) {
    Say "Creating virtualenv at .venv ..."
    & $py[0] $py[1..($py.Length - 1)] -m venv $venv
    if (-not $?) { Fail "virtualenv creation failed." }
}
Ok "virtualenv .venv"

Say "Installing backend dependencies ..."
& $venvPython -m pip install --quiet --upgrade pip
& $venvPython -m pip install --quiet -r (Join-Path $repo "backend\requirements.txt")
if (-not $?) { Fail "pip install failed." }
Ok "backend dependencies installed"

# --- static UI -------------------------------------------------------------------
if ($SkipUi) {
    if (-not (Test-Path (Join-Path $repo "frontend\out\index.html"))) { Fail "-SkipUi was given but frontend/out/index.html does not exist." }
    Ok "UI build skipped (frontend/out present)"
} else {
    Push-Location (Join-Path $repo "frontend")
    try {
        if (Test-Path "package-lock.json") { & npm ci --no-audit --no-fund } else { & npm install --no-audit --no-fund }
        if (-not $?) { Fail "npm install failed." }
        & npm run build
        if (-not $?) { Fail "npm run build failed." }
    } finally { Pop-Location }
    if (-not (Test-Path (Join-Path $repo "frontend\out\index.html"))) { Fail "build finished but frontend/out/index.html is missing." }
    Ok "UI built into frontend/out"
}

# --- .env ------------------------------------------------------------------------
$envFile = Join-Path $repo ".env"
if (-not (Test-Path $envFile)) {
    $secret = & $venvPython -c "import secrets;print(secrets.token_urlsafe(48))"
    $lines = @(
        "# Infra Monitor -- native install. Generated by scripts/native-setup.ps1.",
        "",
        "APP_PORT=8088",
        "",
        "# Signs JWTs AND derives the Fernet key for stored SSH credentials. Back this file",
        "# up together with data/inframonitor.db, and do not change it after servers are",
        "# onboarded or their stored credentials become permanently unreadable.",
        "JWT_SECRET=$secret",
        "",
        "ACCESS_TOKEN_EXPIRE_MINUTES=480",
        "",
        "# Same-origin: the UI is served by the same process as the API.",
        "CORS_ORIGINS=",
        "",
        "DATABASE_URL=sqlite:///./data/inframonitor.db"
    )
    Set-Content -Path $envFile -Value $lines -Encoding utf8
    Ok ".env created with a generated JWT_SECRET"
} else {
    Ok ".env already present (left untouched)"
}

# --- data directory --------------------------------------------------------------
$dataDir = Join-Path $repo "data"
if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir | Out-Null }

# An earlier ad-hoc run may have left a database under backend/data. The native run
# uses the repo root as its working directory, so move it rather than silently
# starting with an empty inventory beside a populated file nobody looks at.
$legacy = Join-Path $repo "backend\data\inframonitor.db"
$target = Join-Path $dataDir "inframonitor.db"
if ((Test-Path $legacy) -and (-not (Test-Path $target))) {
    # Never move a live SQLite database: the -wal holds committed data that has not been
    # checkpointed into the main file yet, so moving one while a process has it open can
    # leave both halves inconsistent. Check for a writer lock and refuse instead.
    $locked = $false
    try {
        $stream = [System.IO.File]::Open($legacy, "Open", "ReadWrite", "None")
        $stream.Close()
    } catch { $locked = $true }

    if ($locked) {
        Write-Host "WARN  data/ is ready, but backend/data/inframonitor.db is open in another process." -ForegroundColor Yellow
        Write-Host "      Stop whatever is using it, then re-run this script to migrate it."
        Write-Host "      Until then the native run would start against an empty database."
    } else {
        Say "Migrating existing database from backend/data to data/ ..."
        foreach ($suffix in @("", "-wal", "-shm")) {
            $from = "$legacy$suffix"
            if (Test-Path $from) { Move-Item -Path $from -Destination "$target$suffix" }
        }
        Ok "database migrated to data/inframonitor.db"
    }
}
Ok "data directory ready"

Say ""
Say "Setup complete. Start it with:"
Say "    powershell -ExecutionPolicy Bypass -File scripts\native-run.ps1"
Say ""
